### ISSUE TITLE
One Sheet for Project

### ISSUE THREAD

**Issue by phoebeng** [hackforla/community-survey-nc-websites#1]
### Overview

Write a one-sheet for the City Survey project including milestones for the next 6 months.

### Dependency
Needs an updated logo

### Action Items

- [x] Review VRMS one-sheet
- [x] Review another project examples one-sheet
- [x] Review presentation in the Google Drive
- [x] Produce First Draft of [One-Sheet on Google Drive](https://docs.google.com/document/d/1-1JHqX2JiZjaba19JM2svf8KKdVDuuCT01oXEVsQltU/edit)
- [x] Tag Bonnie to add details for History and Future on One-Sheet
- [x] Prepare questions for review with Bonnie

### Resources/Instructions
[Project One Sheet](https://docs.google.com/document/d/1-1JHqX2JiZjaba19JM2svf8KKdVDuuCT01oXEVsQltU/edit)
[All Project One Sheets](https://github.com/hackforla/product-managment/issues/3)
[VRMS Doc](https://docs.google.com/document/d/1lsRUAAMs1b60LOqQb9H6c4Ky9AbQ7QN4FB1XNErKxEs/edit)
[Civic Opportunity Project One-Sheet](https://github.com/hackforla/civic-opportunity/blob/master/Civic_Opportunity_Project_OnePage.pdf)
[Project Presentation](https://docs.google.com/presentation/d/1otdFmrWG24hYwfIgN6eutEkA4gEg20cwNtIBydQw6o0/edit#slide=id.ga37927f1df_0_137)

**Comment by ExperimentsInHonesty** [comment]
@ExperimentsInHonesty will add email address to one sheet.

**Comment by ExperimentsInHonesty** [comment]
@phoebeng Update the doc 

- [x] to have a font color that best matches the design while being dark enough to read
- [x] add logo

**Comment by ExperimentsInHonesty** [comment]
Hi @phoebeng this was in the icebox.  It seems done.  Am I forgetting something?
