### ISSUE TITLE
Create Logo

### ISSUE THREAD

**Issue by phoebeng** [hackforla/community-survey-nc-websites#10]
### Overview
We need a logo to communicate the purpose of this project in a visual way. 

### Action Items
- [x] Review existing logo
- [x] Edit to meet new criteria 
- [x] update the following issue
   - [x] Create project card #2 
   - [x] Create one sheet #1 

### Resources/Instructions
![hero_image](https://user-images.githubusercontent.com/43743179/104961066-6e8c9d00-598a-11eb-8b47-c9d7872d5206.jpg)
![logo](https://user-images.githubusercontent.com/43743179/104961080-7c422280-598a-11eb-849f-84a9fd1927ee.jpg)

**Comment by phoebeng** [comment]
![logo_final](https://user-images.githubusercontent.com/43743179/106405441-11adcf80-63eb-11eb-8b1d-46447bc89f78.jpg)
![hero_final](https://user-images.githubusercontent.com/43743179/106405450-15d9ed00-63eb-11eb-84b1-420cf531ddf6.jpg)

**Comment by ExperimentsInHonesty** [comment]
shoes different colors than gray
jacket color other than blue
dark orange house moved forward and add a house behind it (duplex)

**Comment by ExperimentsInHonesty** [comment]
This looks awesome.  Its now been added to the page card and one sheet and project board
