### ISSUE TITLE
Find a Partner: Representative Sample Survey

### ISSUE THREAD

**Issue by phoebeng** [hackforla/community-survey-nc-websites#14]
### Overview
We are trying to find a partner on the cutting edge of bias reduction and representative sampling, who works in the industry or academia so that we can recommend them to our city partners when asked, and to help us craft our practice.

### Action Items
- [ ] Send out messages to network
  - [ ] Code for America
  - [ ] Hack for LA 

### Resources/Instructions

> We are looking to partner with a firm or person that that does polls/surveys like Gallup or Pew Institute experienced in creating surveys that reduce bias, and who understands the importance of representative sampling, etc.  

> If you know of anyone we should contact, please add them in a comment on this [issue](https://github.com/hackforla/community-survey-nc-websites/issues/14) , or if you have any questions, please reach out to @Phoebe Ng

**Comment by ExperimentsInHonesty** [comment]
I sent out a slack message today on general

**Comment by ExperimentsInHonesty** [comment]
I sent out a slack message today

**Comment by superbunker** [comment]
Data for Progress might be an option - https://www.dataforprogress.org/

I don't have any contacts there, but their polls are pretty good, and they specifically work with "movement organizations"

**Comment by phoebeng** [comment]
The Behavioral Insights Team: https://www.bi.team/about-us/ 

Suggested to me from Code for America Slack.

**Comment by phoebeng** [comment]
Julian found someone
