### ISSUE TITLE
Increase ratio of image on hackforla.org project page for Open Community Survey to 3:2

### ISSUE THREAD

**Issue by shaswa** [hackforla/community-survey-nc-websites#16]
### Overview
All  project images on the [hackforla homepage projects section](https://www.hackforla.org/#projects) should have a 3:2 ratio and a standard resolution of 600x400 pixels or higher. 

Current Resolution: 2501 x 1668 pixels
Current Ratio: 2.999:2

### Action Items

- [ ] Increase ratio of project image for Open Community Survey to 3:2
- [ ] Update Status on hackforla/website#1105

### Resources/Instructions
[Projects page](https://www.hackforla.org/#projects)
[Image](https://www.hackforla.org/assets/images/projects/open-community-survey.jpg)

**Comment by shaswa** [comment]
@phoebeng Could you provide an update for this issue?

**Comment by phoebeng** [comment]
![open_com_survey_nc_logo-05](https://user-images.githubusercontent.com/43743179/112904679-22528d00-909e-11eb-89ee-7349c5f26850.jpg)
I think this should be the right ratio! Let me know if I need to change anything!

**Comment by ExperimentsInHonesty** [comment]
I added a smaller version and opened an issue on hackforla website team https://github.com/hackforla/website/issues/1342
![open-community-survey](https://user-images.githubusercontent.com/37763229/113189247-d6275a00-920f-11eb-8694-cb3de4fcb1fb.jpg)
